name: Build Check

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
    branches:
      - main
      - v4
  schedule:
    - cron: '15 4 * * *' # build runs every weekday at 4:15AM UTC

env:
  FORCE_COLOR: 2
  NODE: 18

jobs:
  build:
    runs-on: windows-latest  # Use your desired platform (can also be macOS-latest)
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x  # Node.js version

      - name: Install npm dependencies
        run: npm install

      - name: Run build
        run: npm run build
